### ISSUE TITLE
ENOSPC 

### ISSUE THREAD

**Issue by mfonsos** [beefsack/node-hound#17]
Hello,

I cannot find why i get the following error.

Error: watch server/prints/agparaskeui/receiptseyp ENOSPC
at exports._errnoException (util.js:870:11)
at FSWatcher.start (fs.js:1234:19)
at fs.watch (fs.js:1262:11)
at Hound.watch (/var/www/bullseye/server/node_modules/hound/hound.js:52:24)
at Object.exports.watch (/var/www/bullseye/server/node_modules/hound/hound.js:18:11)
at printReceiptTxtProduceEyp (/var/www/bullseye/server/config/printNode.js:1334:50)
at WriteStream.<anonymous> (/var/www/bullseye/server/config/printNode.js:1295:25)
at WriteStream.g (events.js:260:16)
at emitNone (events.js:72:20)
at WriteStream.emit (events.js:166:7)
at finishMaybe (_stream_writable.js:468:14)
at afterWrite (_stream_writable.js:347:3)
at onwrite (_stream_writable.js:337:7)
at WritableState.onwrite (_stream_writable.js:89:5)
at fs.js:1911:5
at FSReqWrap.wrapper [as oncomplete] (fs.js:1878:5)

**Comment by gforceg** [comment]
@mfonsos, 

Sorry for the delay, I took over this node-hound from the original author and was not subscribed to the repository.

ENOSP is a posix error that means the device is full.

Are you low on storage?
